# Generated by Django 4.2.20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('permis_conduire', models.CharField(max_length=50, verbose_name='Numéro de permis')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('conge', 'En congé'), ('arret', 'Arrêt maladie')], default='actif', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50, verbose_name='Marque')),
                ('modele', models.CharField(max_length=50, verbose_name='Modèle')),
                ('immatriculation', models.CharField(max_length=20, unique=True, verbose_name='Immatriculation')),
                ('numero_chassis', models.CharField(max_length=50, unique=True, verbose_name='Numéro de châssis')),
                ('couleur', models.CharField(max_length=30, verbose_name='Couleur')),
                ('annee_fabrication', models.IntegerField(verbose_name='Année de fabrication')),
                ('type_vehicule', models.CharField(choices=[('voiture', 'Voiture'), ('camion', 'Camion'), ('bus', 'Bus'), ('moto', 'Moto'), ('utilitaire', 'Utilitaire')], max_length=30, verbose_name='Type de véhicule')),
                ('type_carburant', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique'), ('hybride', 'Hybride')], max_length=20, verbose_name='Type de carburant')),
                ('capacite_reservoir', models.FloatField(verbose_name='Capacité du réservoir (L)')),
                ('kilometrage', models.IntegerField(default=0, verbose_name='Kilométrage')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_mission', 'En mission'), ('maintenance', 'En maintenance'), ('panne', 'En panne'), ('reforme', 'Réformé')], default='disponible', max_length=20, verbose_name='Statut')),
                ('date_achat', models.DateField(verbose_name="Date d'achat")),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Prix d'achat")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['marque', 'modele', 'immatriculation'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200, verbose_name='Objet de la mission')),
                ('destination', models.CharField(max_length=200, verbose_name='Destination')),
                ('lieu_depart', models.CharField(default='Bureau principal', max_length=200, verbose_name='Lieu de départ')),
                ('date_debut', models.DateTimeField(verbose_name='Date et heure de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('date_retour_prevue', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour prévue')),
                ('date_retour_effective', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour effective')),
                ('km_depart', models.IntegerField(verbose_name='Kilométrage au départ')),
                ('km_retour', models.IntegerField(blank=True, null=True, verbose_name='Kilométrage au retour')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('retard', 'En retard')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('cout_carburant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût carburant')),
                ('autres_frais', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Autres frais')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.chauffeur', verbose_name='Chauffeur')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_demandees', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective'), ('revision', 'Révision'), ('reparation', 'Réparation')], max_length=30, verbose_name='Type de maintenance')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_maintenance', models.DateField(verbose_name='Date de maintenance')),
                ('km_maintenance', models.IntegerField(verbose_name='Kilométrage à la maintenance')),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût')),
                ('garage', models.CharField(max_length=100, verbose_name='Garage/Atelier')),
                ('technicien', models.CharField(max_length=100, verbose_name='Technicien')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_maintenance'],
            },
        ),
    ]
